apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird-exporter.fullname" . }}
  labels:
    {{- include "netbird-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if hasKey .Values.service "clusterIP" }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netbird-exporter.selectorLabels" . | nindent 4 }} 